sensor_msgs/JointState joint_state                      # Configuration at which to calculate Jacobian 
---
constrained_manipulability_interfaces/Matrix jacobian   # Resulting Jacobian as a custom Matrix type