int32 ALLOWABLE_MOTION_POLYTOPE=1
int32 CONSTRAINED_ALLOWABLE_MOTION_POLYTOPE=2
int32 VELOCITY_POLYTOPE=3
int32 CONSTRAINED_VELOCITY_POLYTOPE=4

int32 polytope_type
sensor_msgs/JointState[] joint_states  # Configurations at which to calculate polytope constraints 
bool show_polytope
---
constrained_manipulability_interfaces/Polytope[] polytopes